/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoagenda;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuário
 */
public class Contato extends javax.swing.JFrame {

    /**
     * Creates new form Contatos
     *
     * @param ag
     */
    public Contato(Agenda ag, Main m) {
        this.ag = ag;
        this.m = m;
        initComponents();
        enfeite1.setVisible(false);
        enfeite2.setVisible(false);
        bPrev.setVisible(false);
        bNext.setVisible(false);

    }

    private final Agenda ag;
    private ArrayList<Contatos> contatos;
    private int aux = 0;
    private Contatos contato;
    private final Main m;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        textEnd = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        textDddRes = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textTelRes = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        textDddCom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textTelCom = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bSEE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bCancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bPrev = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bNext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        enfeite2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        enfeite1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Constantes.getVersion());
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Nome: ");
        jPanel6.add(jLabel16);
        jPanel6.add(textNome);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Endereco: ");
        jPanel7.add(jLabel17);
        jPanel7.add(textEnd);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("E-mail: ");
        jPanel8.add(jLabel18);
        jPanel8.add(textEmail);

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(2, 2));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("DDD Res.: ");
        jPanel9.add(jLabel19);
        jPanel9.add(textDddRes);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Tel. Res.: ");
        jPanel9.add(jLabel20);
        jPanel9.add(textTelRes);

        jPanel1.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(2, 2));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("DDD Com.: ");
        jPanel10.add(jLabel21);
        jPanel10.add(textDddCom);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Tel. Com.: ");
        jPanel10.add(jLabel22);
        jPanel10.add(textTelCom);

        jPanel1.add(jPanel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));
        jPanel2.add(jLabel1);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Adicao/Edicao de ####");
        jPanel2.add(labelTitulo);
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(3, 5));
        jPanel3.add(jLabel2);
        jPanel3.add(jLabel4);
        jPanel3.add(jLabel5);
        jPanel3.add(jLabel6);
        jPanel3.add(jLabel7);
        jPanel3.add(jLabel15);

        bSEE.setText("Salvar");
        bSEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSEEActionPerformed(evt);
            }
        });
        jPanel3.add(bSEE);
        jPanel3.add(jLabel8);

        bCancel.setText("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel3.add(bCancel);
        jPanel3.add(jLabel9);

        bPrev.setText("<");
        bPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrevActionPerformed(evt);
            }
        });
        jPanel3.add(bPrev);
        jPanel3.add(jLabel11);
        jPanel3.add(jLabel12);
        jPanel3.add(jLabel13);

        bNext.setText(">");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });
        jPanel3.add(bNext);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        enfeite2.setText("ENF");
        jPanel4.add(enfeite2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        enfeite1.setText("ENF");
        jPanel5.add(enfeite1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSEEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSEEActionPerformed
        boolean aux = true;
        switch (bSEE.getText()) {
            case "Incluir":
                try {
                    ag.Incluir(new Contatos("",
                            textNome.getText(),
                            textEnd.getText(),
                            ag.ValidaEmail(textEmail.getText()),
                            ag.ValidaTelefone(textDddRes.getText(), textTelRes.getText(), 0),
                            ag.ValidaTelefone(textDddCom.getText(), textTelCom.getText(), 1)));
                } catch (NumberFormatException ex) {
                    Logger.getLogger(Contato.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "DDD ou Telefone invalido para residencial e/ou comercial!");
                    aux = false;
                } catch (Exception ex) {
                    Logger.getLogger(Contato.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "E-mail invalido!");
                    aux = false;
                }
                break;
            case "Editar": {
                try {
                    ag.Editar(new Contatos(contato.getIndice(),
                            textNome.getText(),
                            textEnd.getText(),
                            ag.ValidaEmail(textEmail.getText()),
                            ag.ValidaTelefone(textDddRes.getText(), textTelRes.getText(), 0),
                            ag.ValidaTelefone(textDddCom.getText(), textTelCom.getText(), 1)));
                } catch (NumberFormatException ex) {
                    Logger.getLogger(Contato.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "DDD ou Telefone invalido para residencial e/ou comercial!");
                    aux = false;
                } catch (Exception ex) {
                    Logger.getLogger(Contato.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "E-mail invalido!");
                    aux = false;
                }
            }
            break;
            case "Excluir":
                ag.Excluir(contato);
                break;
        }
        if (aux) {
            this.setVisible(false);
            m.setVisible(true);
        }
    }//GEN-LAST:event_bSEEActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_bCancelActionPerformed

    private void bPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrevActionPerformed
        if (aux > 0) {
            doScreen(--aux);
            if (aux == 0) {
                bPrev.setVisible(false);
                bNext.setVisible(true);
            } else {
                bPrev.setVisible(true);
                bNext.setVisible(true);
            }
        }
    }//GEN-LAST:event_bPrevActionPerformed

    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        if (aux < contatos.size() - 1) {
            doScreen(++aux);            
            if (aux == contatos.size() - 1) {
                bNext.setVisible(false);
                bPrev.setVisible(true);
            } else {
                bPrev.setVisible(true);
                bNext.setVisible(true);
            }
        }
    }//GEN-LAST:event_bNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bPrev;
    private javax.swing.JButton bSEE;
    private javax.swing.JLabel enfeite1;
    private javax.swing.JLabel enfeite2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textDddCom;
    private javax.swing.JTextField textDddRes;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEnd;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelCom;
    private javax.swing.JTextField textTelRes;
    // End of variables declaration//GEN-END:variables

    public void setLabelTitulo(String labelTitulo) {
        this.labelTitulo.setText(labelTitulo);
    }

    public javax.swing.JTextField getTextDddCom() {
        return textDddCom;
    }

    public void setTextDddCom(String textDddCom) {
        this.textDddCom.setText(textDddCom);
    }

    public javax.swing.JTextField getTextDddRes() {
        return textDddRes;
    }

    public void setTextDddRes(String textDddRes) {
        this.textDddRes.setText(textDddRes);
    }

    public javax.swing.JTextField getTextEmail() {
        return textEmail;
    }

    public void setTextEmail(String textEmail) {
        this.textEmail.setText(textEmail);
    }

    public javax.swing.JTextField getTextEnd() {
        return textEnd;
    }

    public void setTextEnd(String textEnd) {
        this.textEnd.setText(textEnd);
    }

    public javax.swing.JTextField getTextNome() {
        return textNome;
    }

    public void setTextNome(String textNome) {
        this.textNome.setText(textNome);
    }

    public javax.swing.JTextField getTextTelCom() {
        return textTelCom;
    }

    public void setTextTelCom(String textTelCom) {
        this.textTelCom.setText(textTelCom);
    }

    public javax.swing.JTextField getTextTelRes() {
        return textTelRes;
    }

    public void setTextTelRes(String textTelRes) {
        this.textTelRes.setText(textTelRes);
    }

    public void setbSEE(String bSEE) {
        this.bSEE.setText(bSEE);
    }

    public void setAllEditable(boolean b) {
        this.textNome.setEditable(b);
        this.textEnd.setEditable(b);
        this.textEmail.setEditable(b);
        this.textDddRes.setEditable(b);
        this.textTelRes.setEditable(b);
        this.textDddCom.setEditable(b);
        this.textTelCom.setEditable(b);
    }

    public void CleanAll() {
        this.textNome.setText("");
        this.textEnd.setText("");
        this.textEmail.setText("");
        this.textDddRes.setText("");
        this.textTelRes.setText("");
        this.textDddCom.setText("");
        this.textTelCom.setText("");
    }

    public void setContatos(ArrayList<Contatos> contatos) {
        this.contatos = contatos;
        if (contatos.size() <= 1) {
            bPrev.setVisible(false);
            bNext.setVisible(false);
        } else {
            bPrev.setVisible(false);
            bNext.setVisible(true);
        }
    }

    public void doScreen(int i) {
        aux = i;
        contato = contatos.get(i);
        this.textNome.setText(contato.getNome());
        this.textEnd.setText(contato.getEndereco());
        this.textEmail.setText(contato.getEmail());
        this.textDddRes.setText(contato.getTelres().split("#")[0]);
        this.textTelRes.setText(contato.getTelres().split("#")[1]);
        this.textDddCom.setText(contato.getTelcom().split("#")[0]);
        this.textTelCom.setText(contato.getTelcom().split("#")[1]);
    }

    public void setbCancel(boolean b) {
        this.bCancel.setVisible(b);
    }
}
